name: Build and Compile
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run backend
        run: |
          cd backend
          node app.js
          
      - name: run frontend
        run: |
          cd frontend
          npm start

