name: Build and Compile
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: installing dependencies
        run: |
          npm i cors
          npm i express
          npm i morgan
          npm i swagger-jsdoc
          npm i mongoose
          npm i swagger-ui-express
          npm i express-validator
          npm i uuid
          npm i multer
          npm i react-scripts
          

